
FROM node:18-alpine


WORKDIR /app


RUN apk update && apk add --no-cache \
  openssl \
  bash \
  && rm -rf /var/cache/apk/*


COPY backend/package*.json ./


RUN npm install


COPY backend/ .


ENV DATABASE_URL="file:./dev.db"


RUN npm run build


EXPOSE 5000


CMD ["npm", "start"]
