FROM node:18-alpine


WORKDIR /app


ARG - VITE_API_BASE_URL


ENV VITE_API_BASE_URL=$VITE_API_BASE_URL


COPY frontend/package*.json ./


RUN npm install

COPY frontend/ .


RUN npm run build

RUN npm install -g serve


EXPOSE 3000


CMD ["serve","-s", "dist"]
